version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 50
  target-branch: main
  reviewers:
  - strokesws
  assignees:
  - strokesws
